/**
 * ACCIDENT NETWORKS — Master City Data
 * One row per state. This is the source of truth.
 * Export to Google Sheets for client editing.
 * Build script compiles each row into /configs/[id].js
 */

const CITY_DATA = [
  {
    id: "birmingham",
    city: "Birmingham",
    state: "Alabama",
    stateCode: "AL",
    county: "Jefferson County",
    phone: "205-600-0000",
    lat: 33.5186, lng: -86.8104,
    statute: "2 years",
    pip: false,
    faultState: "contributory negligence",
    highways: ["I-20", "I-65", "I-459", "I-22", "US-78", "US-280"],
    landmarks: ["Vulcan Park", "UAB Medical Center", "Sloss Furnaces", "Railroad Park", "Regions Field", "Five Points South"],
    neighborhoods: ["Hoover", "Vestavia Hills", "Homewood", "Trussville", "Alabaster", "Pelham", "Gardendale"],
    hotspots: ["I-65 at I-20/59 interchange", "US-280 corridor", "I-459 beltway", "Malfunction Junction"],
    medCenters: ["UAB Hospital", "Brookwood Baptist Medical Center", "St. Vincent's Birmingham"],
    airports: ["Birmingham-Shuttlesworth International Airport (BHM)"],
    localFacts: ["Alabama is a contributory negligence state", "Birmingham has one of the highest crash rates per capita in the Southeast", "Jefferson County logs over 12,000 crashes annually"]
  },
  {
    id: "anchorage",
    city: "Anchorage",
    state: "Alaska",
    stateCode: "AK",
    county: "Anchorage Municipality",
    phone: "907-600-0000",
    lat: 61.2181, lng: -149.9003,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["Glenn Highway", "Seward Highway", "Minnesota Drive", "New Seward Highway", "Old Seward Highway", "Tudor Road"],
    landmarks: ["Alaska Native Medical Center", "Providence Alaska Medical Center", "Delaney Park Strip", "Ship Creek", "Tony Knowles Coastal Trail"],
    neighborhoods: ["Eagle River", "South Anchorage", "Midtown", "Fairview", "Spenard", "Muldoon", "Abbott Loop"],
    hotspots: ["Seward Highway near Rabbit Creek", "Glenn Highway at Muldoon", "Tudor Road corridor", "Minnesota Drive at Benson"],
    medCenters: ["Alaska Native Medical Center", "Providence Alaska Medical Center", "Alaska Regional Hospital"],
    airports: ["Ted Stevens Anchorage International Airport (ANC)"],
    localFacts: ["Alaska winters create significant black ice accident risk", "Moose crossings are a leading cause of non-collision accidents", "Anchorage logs over 3,000 crashes annually despite its size"]
  },
  {
    id: "phoenix",
    city: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    county: "Maricopa County",
    phone: "602-600-0000",
    lat: 33.4484, lng: -112.0740,
    statute: "2 years",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-10", "I-17", "Loop 101", "Loop 202", "Loop 303", "US-60", "SR-51", "SR-143"],
    landmarks: ["Banner University Medical Center", "St. Joseph's Hospital", "Sky Harbor Airport", "Camelback Mountain", "Arizona State University", "Chase Field", "Footprint Center"],
    neighborhoods: ["Scottsdale", "Tempe", "Mesa", "Chandler", "Gilbert", "Glendale", "Peoria", "Surprise", "Avondale"],
    hotspots: ["I-10 at I-17 Stack interchange", "Loop 101 corridor", "US-60 in Mesa", "I-10 at Baseline Road", "Loop 202 South Mountain Freeway"],
    medCenters: ["Banner University Medical Center", "Dignity Health St. Joseph's", "HonorHealth Scottsdale Osborn"],
    airports: ["Phoenix Sky Harbor International Airport (PHX)", "Phoenix Deer Valley Airport"],
    localFacts: ["Maricopa County ranks among the top 5 counties nationally for traffic fatalities", "Arizona monsoon season (June-September) causes dangerous road flooding", "Phoenix sees over 60,000 crashes annually across Maricopa County"]
  },
  {
    id: "little-rock",
    city: "Little Rock",
    state: "Arkansas",
    stateCode: "AR",
    county: "Pulaski County",
    phone: "501-600-0000",
    lat: 34.7465, lng: -92.2896,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-30", "I-40", "I-430", "I-630", "US-65", "US-67", "AR-10", "AR-365"],
    landmarks: ["UAMS Medical Center", "Baptist Health Medical Center", "Riverfront Park", "William J. Clinton Presidential Library", "Pinnacle Mountain State Park", "North Little Rock Levee Trail"],
    neighborhoods: ["West Little Rock", "Chenal Valley", "Heights", "Hillcrest", "Maumelle", "Sherwood", "Conway", "Benton"],
    hotspots: ["I-30 at I-430 interchange", "I-40 west corridor", "Cantrell Road", "Rodney Parham Road", "Colonel Glenn Road"],
    medCenters: ["UAMS Medical Center", "Baptist Health Medical Center", "CHI St. Vincent Infirmary"],
    airports: ["Bill and Hillary Clinton National Airport (LIT)"],
    localFacts: ["Arkansas has a 3-year statute of limitations for personal injury", "Pulaski County averages over 8,000 crashes per year", "I-30 reconstruction has significantly increased crash risk in the metro area"]
  },
  {
    id: "los-angeles",
    city: "Los Angeles",
    state: "California",
    stateCode: "CA",
    county: "Los Angeles County",
    phone: "213-600-0000",
    lat: 34.0522, lng: -118.2437,
    statute: "2 years",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-405 San Diego Freeway", "I-10 Santa Monica Freeway", "I-110 Harbor Freeway", "US-101 Hollywood Freeway", "I-5 Golden State Freeway", "SR-60 Pomona Freeway", "SR-134 Ventura Freeway"],
    landmarks: ["Cedars-Sinai Medical Center", "UCLA Medical Center", "Dodger Stadium", "SoFi Stadium", "Hollywood Walk of Fame", "Santa Monica Pier", "Griffith Observatory", "Los Angeles Convention Center"],
    neighborhoods: ["Hollywood", "Santa Monica", "Burbank", "Pasadena", "Long Beach", "Torrance", "El Monte", "Pomona", "Ontario", "Compton"],
    hotspots: ["I-405 at I-10 interchange", "I-101 in Hollywood", "I-10 in Santa Monica", "I-405 Sepulveda Pass", "US-101 Cahuenga Pass"],
    medCenters: ["Cedars-Sinai Medical Center", "UCLA Ronald Reagan Medical Center", "LAC+USC Medical Center", "Kaiser Permanente Los Angeles"],
    airports: ["Los Angeles International Airport (LAX)", "Bob Hope Airport Burbank (BUR)", "Long Beach Airport (LGB)"],
    localFacts: ["California has the most registered vehicles of any state", "LA County records over 50,000 injury crashes annually", "California follows pure comparative fault — you can recover even if partially at fault"]
  },
  {
    id: "denver",
    city: "Denver",
    state: "Colorado",
    stateCode: "CO",
    county: "Denver County",
    phone: "303-600-0000",
    lat: 39.7392, lng: -104.9903,
    statute: "3 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-25", "I-70", "I-270", "I-76", "E-470", "C-470", "US-6 6th Avenue", "US-85 Santa Fe Drive"],
    landmarks: ["Denver Health Medical Center", "UCHealth University of Colorado Hospital", "Coors Field", "Empower Field at Mile High", "Ball Arena", "Denver Union Station", "Red Rocks Amphitheatre", "Denver International Airport"],
    neighborhoods: ["Aurora", "Lakewood", "Arvada", "Westminster", "Thornton", "Englewood", "Littleton", "Centennial", "Parker", "Castle Rock"],
    hotspots: ["I-25 at I-70 interchange (The Mousetrap)", "I-70 mountain corridor", "E-470 beltway", "US-6 at I-25", "I-225 corridor in Aurora"],
    medCenters: ["Denver Health Medical Center", "UCHealth University of Colorado Hospital", "Swedish Medical Center", "St. Joseph Hospital Denver"],
    airports: ["Denver International Airport (DEN)"],
    localFacts: ["Colorado requires minimum $25,000/$50,000 bodily injury coverage", "I-70 mountain corridor is one of the most dangerous interstate segments in the country", "Denver sees over 25,000 crashes annually in the metro area"]
  },
  {
    id: "bridgeport",
    city: "Bridgeport",
    state: "Connecticut",
    stateCode: "CT",
    county: "Fairfield County",
    phone: "203-600-0000",
    lat: 41.1865, lng: -73.1952,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-95 Connecticut Turnpike", "I-91", "Route 15 Merritt Parkway", "Route 8", "US-1 Boston Post Road", "Route 25"],
    landmarks: ["Bridgeport Hospital", "St. Vincent's Medical Center", "McLevy Green", "Seaside Park", "Beardsley Zoo", "Harbor Yard Sports Complex"],
    neighborhoods: ["Stratford", "Milford", "Trumbull", "Shelton", "Derby", "Ansonia", "Fairfield", "Westport"],
    hotspots: ["I-95 through downtown Bridgeport", "Merritt Parkway exits", "Route 8 corridor", "US-1 Boston Post Road", "I-95/Route 8 interchange"],
    medCenters: ["Bridgeport Hospital", "St. Vincent's Medical Center", "Griffin Hospital Derby"],
    airports: ["Tweed New Haven Regional Airport (HVN)", "Westchester County Airport (HPN)"],
    localFacts: ["Connecticut has no-fault PIP coverage up to $5,000", "I-95 through Fairfield County is consistently ranked among the most congested corridors in the Northeast", "Fairfield County logs over 15,000 crashes annually"]
  },
  {
    id: "wilmington",
    city: "Wilmington",
    state: "Delaware",
    stateCode: "DE",
    county: "New Castle County",
    phone: "302-600-0000",
    lat: 39.7447, lng: -75.5484,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-95", "I-495", "Route 1 Delaware Memorial Bridge", "US-13 DuPont Highway", "US-40", "Route 202 Concord Pike"],
    landmarks: ["Christiana Hospital", "Wilmington Hospital", "Rodney Square", "Wilmington Riverfront", "Delaware Art Museum", "Hagley Museum"],
    neighborhoods: ["Newark", "Bear", "Middletown", "Hockessin", "Pike Creek", "Claymont", "New Castle", "Glasgow"],
    hotspots: ["I-95 at Delaware Memorial Bridge", "I-495 split", "Route 202 Concord Pike", "US-13 corridor", "I-95 at Route 1 interchange"],
    medCenters: ["Christiana Hospital", "Wilmington Hospital", "St. Francis Hospital Wilmington"],
    airports: ["Philadelphia International Airport (PHL)", "Wilmington Airport (ILG)"],
    localFacts: ["Delaware has no-fault PIP coverage", "I-95 through Wilmington is one of the busiest freight corridors on the East Coast", "New Castle County averages over 12,000 crashes per year"]
  },
  {
    id: "tampa",
    city: "Tampa",
    state: "Florida",
    stateCode: "FL",
    county: "Hillsborough County",
    phone: "813-706-6813",
    lat: 27.9506, lng: -82.4572,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-275", "I-75", "I-4", "Dale Mabry Highway", "US-19 Gulf to Bay Boulevard", "Crosstown Expressway SR-618", "Veterans Expressway SR-589", "Gandy Boulevard"],
    landmarks: ["Tampa General Hospital", "AdventHealth Tampa", "Raymond James Stadium", "Amalie Arena", "Tropicana Field St. Pete", "Tampa International Airport", "Ybor City", "Hyde Park Village"],
    neighborhoods: ["Brandon", "Clearwater", "St. Petersburg", "Wesley Chapel", "Riverview", "Valrico", "Land O Lakes", "Lutz", "Temple Terrace", "New Tampa"],
    hotspots: ["I-275 at I-4 downtown Tampa interchange", "Dale Mabry Highway full corridor", "I-75 at Bruce B. Downs Boulevard", "Crosstown Expressway SR-618", "US-19 Pinellas County corridor"],
    medCenters: ["Tampa General Hospital", "AdventHealth Tampa", "St. Joseph Hospital Tampa", "HCA Florida South Tampa Hospital"],
    airports: ["Tampa International Airport (TPA)", "St. Pete-Clearwater International Airport (PIE)"],
    localFacts: ["Florida is a no-fault PIP state requiring 10000 minimum PIP coverage", "Florida 2-year statute of limitations took effect in 2023 act fast after any crash", "Hillsborough County records over 35000 crashes annually one of the highest rates in Florida"]
  },
  {
    id: "atlanta",
    city: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    county: "Fulton County",
    phone: "404-600-0000",
    lat: 33.7490, lng: -84.3880,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-285 Perimeter", "I-75", "I-85", "I-20", "I-675", "SR-400 Georgia 400", "I-575", "US-78"],
    landmarks: ["Grady Memorial Hospital", "Piedmont Atlanta Hospital", "Truist Park", "Mercedes-Benz Stadium", "State Farm Arena", "Hartsfield-Jackson Atlanta International Airport", "CNN Center", "Georgia Aquarium", "Centennial Olympic Park"],
    neighborhoods: ["Buckhead", "Midtown", "Decatur", "Sandy Springs", "Dunwoody", "Marietta", "Alpharetta", "Roswell", "Smyrna", "Norcross"],
    hotspots: ["I-285/I-85 interchange (Spaghetti Junction)", "I-285 Top End", "SR-400 corridor", "I-75/I-85 connector downtown", "I-20 west corridor"],
    medCenters: ["Grady Memorial Hospital", "Piedmont Atlanta Hospital", "Emory University Hospital", "Northside Hospital Atlanta"],
    airports: ["Hartsfield-Jackson Atlanta International Airport (ATL)"],
    localFacts: ["Atlanta has one of the most dangerous interchanges in the US — Spaghetti Junction at I-285/I-85", "Georgia follows modified comparative fault at 50% bar", "Fulton County records over 35,000 crashes annually"]
  },
  {
    id: "honolulu",
    city: "Honolulu",
    state: "Hawaii",
    stateCode: "HI",
    county: "Honolulu County",
    phone: "808-600-0000",
    lat: 21.3069, lng: -157.8583,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["H-1 Lunalilo Freeway", "H-2 Moanalua Freeway", "H-3 Windward Viaduct", "Nimitz Highway", "Kamehameha Highway", "Farrington Highway"],
    landmarks: ["The Queen's Medical Center", "Straub Medical Center", "Ala Moana Center", "Diamond Head Crater", "Waikiki Beach", "Pearl Harbor", "Honolulu International Airport", "Aloha Stadium"],
    neighborhoods: ["Waikiki", "Pearl City", "Aiea", "Kailua", "Kaneohe", "Mililani", "Ewa Beach", "Kapolei", "Hawaii Kai"],
    hotspots: ["H-1 through downtown Honolulu", "Zipper Lane on H-1", "Kamehameha Highway near Pearl City", "Nimitz Highway", "H-2 merge onto H-1"],
    medCenters: ["The Queen's Medical Center", "Straub Medical Center", "Kapiolani Medical Center", "Pali Momi Medical Center"],
    airports: ["Daniel K. Inouye International Airport (HNL)"],
    localFacts: ["Hawaii has mandatory no-fault PIP coverage", "Hawaii's limited highway network means accidents cause severe traffic delays", "Honolulu County averages over 10,000 crashes annually"]
  },
  {
    id: "boise",
    city: "Boise",
    state: "Idaho",
    stateCode: "ID",
    county: "Ada County",
    phone: "208-600-0000",
    lat: 43.6150, lng: -116.2023,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-84", "I-184 Connector", "US-20/26 Chinden Boulevard", "US-30", "SH-55 Eagle Road", "SH-21", "Overland Road"],
    landmarks: ["St. Luke's Boise Medical Center", "St. Alphonsus Regional Medical Center", "Taco Bell Arena", "Simplot Sports Complex", "Boise Depot", "Julia Davis Park", "Idaho State Capitol"],
    neighborhoods: ["Meridian", "Nampa", "Eagle", "Garden City", "Star", "Kuna", "Caldwell", "Middleton"],
    hotspots: ["I-84 at I-184 split", "Eagle Road corridor", "Chinden Boulevard US-20/26", "Overland Road at Cole Road", "I-84 Nampa interchange"],
    medCenters: ["St. Luke's Boise Medical Center", "St. Alphonsus Regional Medical Center", "West Valley Medical Center"],
    airports: ["Boise Airport (BOI)"],
    localFacts: ["Boise is one of the fastest-growing metros in the US, increasing crash rates significantly", "Ada County crash rates have doubled in the past decade due to population growth", "Idaho follows modified comparative fault at 50% bar"]
  },
  {
    id: "chicago",
    city: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    county: "Cook County",
    phone: "312-600-0000",
    lat: 41.8781, lng: -87.6298,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-90/94 Dan Ryan Expressway", "I-290 Eisenhower Expressway", "I-55 Stevenson Expressway", "I-57", "I-294 Tri-State Tollway", "I-88 East-West Tollway", "I-190 O'Hare Expressway", "US-41 Lake Shore Drive"],
    landmarks: ["Northwestern Memorial Hospital", "University of Chicago Medicine", "Soldier Field", "United Center", "Wrigley Field", "Millennium Park", "Navy Pier", "McCormick Place", "Willis Tower"],
    neighborhoods: ["Oak Park", "Evanston", "Naperville", "Schaumburg", "Arlington Heights", "Skokie", "Cicero", "Berwyn", "Joliet", "Aurora"],
    hotspots: ["Dan Ryan at I-290 merge", "I-90/94 Jane Byrne interchange", "I-294 at O'Hare", "I-55 at I-90/94", "Lake Shore Drive S-curves"],
    medCenters: ["Northwestern Memorial Hospital", "Rush University Medical Center", "University of Chicago Medicine", "Stroger Hospital of Cook County"],
    airports: ["O'Hare International Airport (ORD)", "Midway International Airport (MDW)"],
    localFacts: ["Illinois follows modified comparative fault at 50% bar", "Cook County records over 100,000 crashes annually", "Chicago's expressway system carries some of the heaviest commercial truck traffic in the nation"]
  },
  {
    id: "indianapolis",
    city: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    county: "Marion County",
    phone: "317-600-0000",
    lat: 39.7684, lng: -86.1581,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-65", "I-70", "I-74", "I-465 Beltway", "I-69", "US-31", "US-40", "SR-37"],
    landmarks: ["Indiana University Health Methodist Hospital", "Eskenazi Health", "Lucas Oil Stadium", "Gainbridge Fieldhouse", "Indiana Convention Center", "Indianapolis Motor Speedway", "White River State Park"],
    neighborhoods: ["Carmel", "Fishers", "Greenwood", "Lawrence", "Noblesville", "Westfield", "Avon", "Plainfield", "Greenfield"],
    hotspots: ["I-465 beltway entire loop", "I-65 at I-70 north split", "I-70 east corridor", "I-69 north corridor", "US-31 corridor in Carmel"],
    medCenters: ["Indiana University Health Methodist Hospital", "Eskenazi Health", "Franciscan Health Indianapolis", "Community Health Network"],
    airports: ["Indianapolis International Airport (IND)"],
    localFacts: ["Indiana averages over 800 traffic fatalities annually", "I-465 beltway is one of the most dangerous urban beltways in the Midwest", "Marion County records over 25,000 crashes per year"]
  },
  {
    id: "des-moines",
    city: "Des Moines",
    state: "Iowa",
    stateCode: "IA",
    county: "Polk County",
    phone: "515-600-0000",
    lat: 41.5868, lng: -93.6250,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-35", "I-80", "I-235", "US-6", "US-65", "IA-5 South Beltline", "IA-28", "Merle Hay Road"],
    landmarks: ["UnityPoint Health Iowa Methodist", "Mercy Medical Center Des Moines", "Wells Fargo Arena", "Principal Park", "Iowa State Capitol", "Iowa Events Center", "Adventureland Park"],
    neighborhoods: ["Ankeny", "West Des Moines", "Urbandale", "Johnston", "Clive", "Waukee", "Altoona", "Pleasant Hill", "Grimes"],
    hotspots: ["I-35/80 merge at Des Moines", "I-235 through downtown", "Merle Hay Road corridor", "I-35 at Ankeny", "I-80 east corridor"],
    medCenters: ["UnityPoint Health Iowa Methodist", "Mercy Medical Center Des Moines", "Broadlawns Medical Center", "MercyOne Des Moines"],
    airports: ["Des Moines International Airport (DSM)"],
    localFacts: ["Iowa's modified comparative fault bars recovery at 51%", "Polk County averages over 15,000 crashes annually", "I-35/80 merge corridor is consistently Iowa's highest-crash roadway segment"]
  },
  {
    id: "wichita",
    city: "Wichita",
    state: "Kansas",
    stateCode: "KS",
    county: "Sedgwick County",
    phone: "316-600-0000",
    lat: 37.6872, lng: -97.3301,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-135", "I-235", "US-54 Kellogg Avenue", "US-400 Kellogg East", "US-81", "K-96", "K-15", "West Kellogg Drive"],
    landmarks: ["Wesley Medical Center", "Via Christi St. Francis", "INTRUST Bank Arena", "Truist Stadium", "Sedgwick County Zoo", "Old Town Wichita", "Botanica Wichita"],
    neighborhoods: ["Andover", "Derby", "Maize", "Goddard", "Park City", "Valley Center", "Haysville", "Bel Aire"],
    hotspots: ["Kellogg US-54 entire corridor", "I-135 at Kellogg", "K-96 west corridor", "I-235 beltway", "US-81 north corridor"],
    medCenters: ["Wesley Medical Center", "Via Christi St. Francis", "Kansas Surgery and Recovery Center"],
    airports: ["Wichita Dwight D. Eisenhower National Airport (ICT)"],
    localFacts: ["Kansas has no-fault PIP coverage up to $4,500 medical/$900 monthly wage loss", "Kellogg Avenue US-54 is consistently Wichita's most dangerous road corridor", "Sedgwick County records over 18,000 crashes annually"]
  },
  {
    id: "louisville",
    city: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    county: "Jefferson County",
    phone: "502-600-0000",
    lat: 38.2527, lng: -85.7585,
    statute: "1 year",
    pip: true,
    faultState: "no-fault",
    highways: ["I-64", "I-65", "I-71", "I-264 Watterson Expressway", "I-265 Gene Snyder Freeway", "US-31W Preston Highway", "US-42", "US-60"],
    landmarks: ["University of Louisville Hospital", "Norton Healthcare", "KFC Yum! Center", "Churchill Downs", "Louisville Slugger Museum", "Muhammad Ali Center", "Waterfront Park", "Louisville Zoo"],
    neighborhoods: ["St. Matthews", "Jeffersontown", "Shively", "Pleasure Ridge Park", "Fern Creek", "Anchorage", "Okolona", "Middletown", "Shelbyville Road corridor"],
    hotspots: ["I-264 Watterson Expressway beltway", "I-65 at I-64 interchange (Spaghetti Junction)", "Gene Snyder Freeway", "Preston Highway", "Bardstown Road corridor"],
    medCenters: ["University of Louisville Hospital", "Norton Children's Hospital", "Baptist Health Louisville", "Jewish Hospital Louisville"],
    airports: ["Louisville Muhammad Ali International Airport (SDF)"],
    localFacts: ["Kentucky has a 1-year statute of limitations — one of the shortest in the nation", "Kentucky is a no-fault state requiring PIP coverage", "Jefferson County records over 28,000 crashes annually"]
  },
  {
    id: "new-orleans",
    city: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    county: "Orleans Parish",
    phone: "504-600-0000",
    lat: 29.9511, lng: -90.0715,
    statute: "1 year",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-10", "I-610", "US-90 Westbank Expressway", "US-61 Airline Drive", "I-310", "LA-23", "Chef Menteur Highway US-90E", "I-10 Twin Span Bridge"],
    landmarks: ["University Medical Center New Orleans", "Tulane Medical Center", "Caesars Superdome", "Smoothie King Center", "Bourbon Street", "French Quarter", "Louis Armstrong International Airport", "City Park"],
    neighborhoods: ["Metairie", "Kenner", "Slidell", "Gretna", "Harvey", "Marrero", "Chalmette", "Westwego", "Terrytown"],
    hotspots: ["I-10 at I-610 split", "I-10 elevated through downtown", "US-90 Westbank Expressway", "I-10 Twin Span Bridge", "Chef Menteur Highway"],
    medCenters: ["University Medical Center New Orleans", "Tulane Medical Center", "Ochsner Medical Center", "East Jefferson General Hospital"],
    airports: ["Louis Armstrong New Orleans International Airport (MSY)"],
    localFacts: ["Louisiana has a 1-year statute of limitations — act fast after any crash", "Louisiana follows pure comparative fault — you can recover even if mostly at fault", "Orleans Parish and surrounding parishes record over 25,000 crashes annually"]
  },
  {
    id: "portland-me",
    city: "Portland",
    state: "Maine",
    stateCode: "ME",
    county: "Cumberland County",
    phone: "207-600-0000",
    lat: 43.6591, lng: -70.2568,
    statute: "6 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-95 Maine Turnpike", "I-295", "US-1 Congress Street", "US-302", "ME-9 Forest Avenue", "ME-77 Cape Elizabeth"],
    landmarks: ["Maine Medical Center", "Mercy Hospital Portland", "Portland Head Light", "Old Port District", "Eastern Promenade", "Portland Sea Dogs Hadlock Field", "Portland Museum of Art"],
    neighborhoods: ["South Portland", "Westbrook", "Scarborough", "Cape Elizabeth", "Gorham", "Falmouth", "Yarmouth", "Biddeford"],
    hotspots: ["I-295 through Portland", "I-95 Maine Turnpike at Exit 44/45", "Forest Avenue ME-9 corridor", "US-1 through Scarborough", "Marginal Way"],
    medCenters: ["Maine Medical Center", "Mercy Hospital Portland", "Southern Maine Health Care"],
    airports: ["Portland International Jetport (PWM)"],
    localFacts: ["Maine has a 6-year statute of limitations — the longest for personal injury in New England", "Maine winters cause significant ice-related crashes", "Cumberland County averages over 6,000 crashes per year"]
  },
  {
    id: "baltimore",
    city: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    county: "Baltimore City",
    phone: "410-600-0000",
    lat: 39.2904, lng: -76.6122,
    statute: "3 years",
    pip: true,
    faultState: "contributory negligence",
    highways: ["I-83 Jones Falls Expressway", "I-95", "I-695 Baltimore Beltway", "I-70", "US-40 Pulaski Highway", "US-1 Baltimore Avenue", "MD-2 Ritchie Highway", "Harbor Tunnel Thruway I-895"],
    landmarks: ["Johns Hopkins Hospital", "University of Maryland Medical Center", "M&T Bank Stadium", "Camden Yards", "Inner Harbor", "National Aquarium", "Pimlico Race Course", "Fort McHenry"],
    neighborhoods: ["Towson", "Columbia", "Catonsville", "Dundalk", "Essex", "Pikesville", "Owings Mills", "White Marsh", "Bel Air"],
    hotspots: ["I-695 beltway entire loop", "I-95 at Fort McHenry Tunnel", "I-83 Jones Falls Expressway", "I-695 at I-95 interchange", "US-40 Pulaski Highway"],
    medCenters: ["Johns Hopkins Hospital", "University of Maryland Medical Center", "University of Maryland Baltimore Washington Medical Center", "MedStar Harbor Hospital"],
    airports: ["Baltimore/Washington International Thurgood Marshall Airport (BWI)"],
    localFacts: ["Maryland is a contributory negligence state — any fault on your part can bar recovery", "Maryland has a 3-year statute of limitations for personal injury", "Baltimore City and County together record over 30,000 crashes annually"]
  },
  {
    id: "boston",
    city: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    county: "Suffolk County",
    phone: "617-600-0000",
    lat: 42.3601, lng: -71.0589,
    statute: "3 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-93", "I-90 Massachusetts Turnpike", "I-95 Route 128", "I-495", "US-1", "Route 2", "Route 9", "Route 16", "Southeast Expressway"],
    landmarks: ["Massachusetts General Hospital", "Brigham and Women's Hospital", "Fenway Park", "TD Garden", "Gillette Stadium (30 min)", "Boston Common", "Faneuil Hall Marketplace", "Logan International Airport"],
    neighborhoods: ["Cambridge", "Somerville", "Quincy", "Brookline", "Newton", "Waltham", "Framingham", "Worcester", "Medford", "Malden"],
    hotspots: ["I-93 at I-90 interchange (the Big Dig)", "Storrow Drive", "Route 128/I-95 belt", "Southeast Expressway I-93 south", "I-90 Mass Pike western section"],
    medCenters: ["Massachusetts General Hospital", "Brigham and Women's Hospital", "Boston Medical Center", "Beth Israel Deaconess Medical Center"],
    airports: ["Boston Logan International Airport (BOS)"],
    localFacts: ["Massachusetts has mandatory no-fault PIP coverage up to $8,000", "Massachusetts has a 3-year statute of limitations", "Suffolk County and surrounding metro record over 50,000 crashes annually"]
  },
  {
    id: "detroit",
    city: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    county: "Wayne County",
    phone: "313-600-0000",
    lat: 42.3314, lng: -83.0458,
    statute: "3 years",
    pip: true,
    faultState: "no-fault",
    highways: ["I-75", "I-94", "I-96", "I-696 Walter P. Reuther Freeway", "I-275", "M-10 Lodge Freeway", "M-39 Southfield Freeway", "US-12 Michigan Avenue"],
    landmarks: ["Detroit Medical Center", "Henry Ford Hospital", "Ford Field", "Little Caesars Arena", "Comerica Park", "Detroit River International Crossing", "Belle Isle Park", "Detroit Institute of Arts"],
    neighborhoods: ["Dearborn", "Warren", "Sterling Heights", "Livonia", "Westland", "Taylor", "Southfield", "Pontiac", "Auburn Hills"],
    hotspots: ["I-75/I-94 interchange downtown Detroit", "I-96 Lodge Freeway through Midtown", "I-696 east/west corridor", "I-75 at I-696", "M-10 Lodge Freeway"],
    medCenters: ["Detroit Medical Center", "Henry Ford Hospital", "Beaumont Hospital Royal Oak", "Sinai-Grace Hospital"],
    airports: ["Detroit Metropolitan Wayne County Airport (DTW)"],
    localFacts: ["Michigan has unlimited no-fault PIP medical coverage (as of 2020 reform)", "Michigan follows no-fault — you collect from your own insurer first", "Wayne County records over 40,000 crashes annually"]
  },
  {
    id: "minneapolis",
    city: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    county: "Hennepin County",
    phone: "612-600-0000",
    lat: 44.9778, lng: -93.2650,
    statute: "6 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-35W", "I-35E", "I-94", "I-394", "I-494", "I-694", "MN-62 Crosstown Highway", "US-169", "US-12"],
    landmarks: ["Hennepin Healthcare", "Regions Hospital", "Target Field", "Target Center", "US Bank Stadium", "Mall of America (Bloomington)", "Minneapolis-St. Paul International Airport", "Lake Calhoun/Bde Maka Ska"],
    neighborhoods: ["St. Paul", "Bloomington", "Plymouth", "Brooklyn Park", "Maple Grove", "Eden Prairie", "Minnetonka", "Edina", "Richfield"],
    hotspots: ["I-35W at I-94 downtown Minneapolis", "I-494 strip in Bloomington", "MN-62 Crosstown", "I-694 east/west", "I-35W south corridor"],
    medCenters: ["Hennepin Healthcare", "Regions Hospital St. Paul", "Abbott Northwestern Hospital", "HCMC Level I Trauma Center"],
    airports: ["Minneapolis-St. Paul International Airport (MSP)"],
    localFacts: ["Minnesota has a 6-year statute of limitations for personal injury", "Minnesota requires no-fault PIP coverage of $40,000", "Hennepin County records over 25,000 crashes annually, with significant ice-related crashes in winter"]
  },
  {
    id: "jackson",
    city: "Jackson",
    state: "Mississippi",
    stateCode: "MS",
    county: "Hinds County",
    phone: "601-600-0000",
    lat: 32.2988, lng: -90.1848,
    statute: "3 years",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-20", "I-55", "I-220", "US-80 Clinton Boulevard", "US-49", "US-51", "MS-18 Robinson Road", "Woodrow Wilson Drive"],
    landmarks: ["University of Mississippi Medical Center", "Merit Health Central", "Trustmark Park", "Mississippi Coliseum", "Mississippi State Capitol", "Mississippi Civil Rights Museum", "LeFleur's Bluff State Park"],
    neighborhoods: ["Flowood", "Brandon", "Ridgeland", "Madison", "Clinton", "Pearl", "Byram", "Richland"],
    hotspots: ["I-20 at I-55 interchange", "I-55 north corridor", "I-220 beltway", "US-80 Clinton Boulevard", "US-49 south corridor"],
    medCenters: ["University of Mississippi Medical Center (UMMC)", "Merit Health Central", "St. Dominic Hospital Jackson"],
    airports: ["Jackson-Medgar Wiley Evers International Airport (JAN)"],
    localFacts: ["Mississippi follows pure comparative fault — you can recover regardless of your percentage of fault", "Mississippi has a 3-year statute of limitations", "Hinds County averages over 8,000 crashes annually"]
  },
  {
    id: "kansas-city",
    city: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    county: "Jackson County",
    phone: "816-600-0000",
    lat: 39.0997, lng: -94.5786,
    statute: "5 years",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-70", "I-35", "I-435 Outer Belt", "I-470", "US-71 Bruce R. Watkins Drive", "US-169", "MO-291", "I-29"],
    landmarks: ["University of Kansas Hospital", "Truman Medical Center", "Arrowhead Stadium", "Kauffman Stadium", "T-Mobile Center", "Power and Light District", "Crown Center", "Union Station"],
    neighborhoods: ["Overland Park", "Lee's Summit", "Independence", "Blue Springs", "Lenexa", "Olathe", "Shawnee", "Leawood", "Liberty"],
    hotspots: ["I-70 at I-435", "I-435 Outer Belt full loop", "US-71 Bruce R. Watkins Drive", "I-35 south corridor", "I-29 north corridor"],
    medCenters: ["University of Kansas Hospital", "Truman Medical Center", "Saint Luke's Hospital Kansas City", "Research Medical Center"],
    airports: ["Kansas City International Airport (MCI)"],
    localFacts: ["Missouri has a 5-year statute of limitations for personal injury", "Missouri follows pure comparative fault — any recovery is possible regardless of fault percentage", "Jackson County records over 20,000 crashes annually"]
  },
  {
    id: "billings",
    city: "Billings",
    state: "Montana",
    stateCode: "MT",
    county: "Yellowstone County",
    phone: "406-600-0000",
    lat: 45.7833, lng: -108.5007,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-90", "I-94", "US-87", "US-212 Laurel Road", "King Avenue West", "24th Street West", "US-312"],
    landmarks: ["Billings Clinic", "St. Vincent Healthcare", "Rimrocks", "MetraPark Arena", "Yellowstone River corridor", "Yellowstone County Fairgrounds", "Chief Plenty Coups State Park"],
    neighborhoods: ["Laurel", "Lockwood", "Shepherd", "Huntley", "Pompeys Pillar", "Columbus", "Hardin"],
    hotspots: ["I-90 through downtown Billings", "King Avenue West corridor", "I-90 at I-94 split", "24th Street West", "US-87 north corridor"],
    medCenters: ["Billings Clinic", "St. Vincent Healthcare", "RiverStone Health"],
    airports: ["Billings Logan International Airport (BIL)"],
    localFacts: ["Montana had no speed limit on certain roads until 1999", "Montana winters produce severe black ice conditions on I-90 and I-94", "Yellowstone County averages over 3,000 crashes annually"]
  },
  {
    id: "omaha",
    city: "Omaha",
    state: "Nebraska",
    stateCode: "NE",
    county: "Douglas County",
    phone: "402-600-0000",
    lat: 41.2565, lng: -95.9345,
    statute: "4 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-80", "I-480 South Freeway", "I-680", "US-75 South 75th Street", "US-6 Dodge Street", "US-275", "NE-38 Q Street", "West Dodge Road"],
    landmarks: ["Nebraska Medicine", "CHI Health Creighton University Medical Center", "TD Ameritrade Park", "CHI Health Center Arena", "Henry Doorly Zoo", "Joslyn Art Museum", "Old Market District"],
    neighborhoods: ["Bellevue", "Papillion", "La Vista", "Ralston", "Gretna", "Millard", "Elkhorn", "Council Bluffs (IA)"],
    hotspots: ["I-80 at I-480 split", "West Dodge Road corridor", "I-680 north loop", "US-75 south corridor", "I-80 at I-680 interchange"],
    medCenters: ["Nebraska Medicine", "CHI Health Creighton University Medical Center", "Methodist Hospital Omaha", "Bergan Mercy Medical Center"],
    airports: ["Eppley Airfield (OMA)"],
    localFacts: ["Nebraska has a 4-year statute of limitations for personal injury", "Nebraska follows modified comparative fault at 50% bar", "Douglas County records over 15,000 crashes annually"]
  },
  {
    id: "las-vegas",
    city: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    county: "Clark County",
    phone: "702-600-0000",
    lat: 36.1699, lng: -115.1398,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-15", "US-95 Boulder Highway", "I-215 Beltway", "US-93 Boulder Highway", "Las Vegas Boulevard (The Strip)", "Summerlin Parkway", "CC-215 Clark County 215"],
    landmarks: ["University Medical Center of Southern Nevada", "Sunrise Hospital", "Allegiant Stadium", "T-Mobile Arena", "MGM Grand", "Bellagio", "Las Vegas Convention Center", "UNLV Campus", "Red Rock Canyon"],
    neighborhoods: ["Henderson", "North Las Vegas", "Summerlin", "Boulder City", "Spring Valley", "Enterprise", "Whitney", "Paradise"],
    hotspots: ["I-15 at I-215 interchange", "Las Vegas Boulevard (The Strip)", "US-95 north of downtown", "I-215 Beltway full loop", "Tropicana Avenue at I-15"],
    medCenters: ["University Medical Center of Southern Nevada", "Sunrise Hospital and Medical Center", "Valley Hospital Medical Center", "Spring Valley Hospital"],
    airports: ["Harry Reid International Airport (LAS)"],
    localFacts: ["Nevada follows modified comparative fault at 50% bar", "Clark County records over 50,000 crashes annually", "Las Vegas Boulevard The Strip is one of the most pedestrian-crash-heavy corridors in the country"]
  },
  {
    id: "manchester",
    city: "Manchester",
    state: "New Hampshire",
    stateCode: "NH",
    county: "Hillsborough County",
    phone: "603-600-0000",
    lat: 42.9956, lng: -71.4548,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-93", "I-293 Everett Turnpike", "US-3", "NH-101 West", "NH-28 Candia Road", "Elm Street", "South Willow Street"],
    landmarks: ["Elliot Hospital", "Catholic Medical Center", "SNHU Arena", "Southern New Hampshire University Campus", "Millyard Museum", "Arms Park", "Manchester-Boston Regional Airport"],
    neighborhoods: ["Bedford", "Goffstown", "Hooksett", "Auburn", "Londonderry", "Derry", "Merrimack", "Nashua"],
    hotspots: ["I-93 through Manchester", "I-293 Everett Turnpike", "South Willow Street corridor", "US-3 at NH-101 interchange", "Elm Street downtown"],
    medCenters: ["Elliot Hospital", "Catholic Medical Center", "Parkland Medical Center Derry"],
    airports: ["Manchester-Boston Regional Airport (MHT)"],
    localFacts: ["New Hampshire has a 3-year statute of limitations", "New Hampshire does not require PIP/no-fault coverage", "Hillsborough County averages over 6,000 crashes annually"]
  },
  {
    id: "newark",
    city: "Newark",
    state: "New Jersey",
    stateCode: "NJ",
    county: "Essex County",
    phone: "973-600-0000",
    lat: 40.7357, lng: -74.1724,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-78", "I-95 New Jersey Turnpike", "I-280", "I-287", "US-1/9 Raymond Boulevard", "US-22", "Route 21 McCarter Highway", "Garden State Parkway"],
    landmarks: ["University Hospital Newark", "Newark Beth Israel Medical Center", "Prudential Center", "Newark Liberty International Airport", "NJPAC", "Branch Brook Park", "Ironbound District"],
    neighborhoods: ["Elizabeth", "Irvington", "East Orange", "Bloomfield", "Belleville", "Nutley", "Kearny", "Harrison"],
    hotspots: ["NJ Turnpike through Newark", "I-78 at I-95 interchange", "I-280 east/west corridor", "US-1/9 corridor", "Garden State Parkway at Newark"],
    medCenters: ["University Hospital Newark", "Newark Beth Israel Medical Center", "Trinitas Regional Medical Center", "Hackensack University Medical Center"],
    airports: ["Newark Liberty International Airport (EWR)"],
    localFacts: ["New Jersey has mandatory no-fault PIP coverage", "New Jersey has a 2-year statute of limitations", "Essex County and the I-95 NJ Turnpike corridor are among the most crash-intensive in the nation"]
  },
  {
    id: "albuquerque",
    city: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    county: "Bernalillo County",
    phone: "505-600-0000",
    lat: 35.0844, lng: -106.6504,
    statute: "3 years",
    pip: false,
    faultState: "pure comparative fault",
    highways: ["I-25", "I-40", "US-550 Paseo del Norte", "NM-47", "Coors Boulevard NM-45", "Central Avenue Route 66", "Unser Boulevard", "Montano Road"],
    landmarks: ["University of New Mexico Hospital", "Presbyterian Hospital Albuquerque", "Isotopes Park", "Kirtland Air Force Base", "Sandia Mountains", "Old Town Albuquerque", "Balloon Fiesta Park"],
    neighborhoods: ["Rio Rancho", "South Valley", "Paradise Hills", "Corrales", "Bernalillo", "Los Ranchos de Albuquerque", "Four Hills", "Tijeras"],
    hotspots: ["I-25 at I-40 Big I interchange", "Central Avenue Route 66 corridor", "Coors Boulevard entire corridor", "I-25 south corridor", "I-40 west through Albuquerque"],
    medCenters: ["University of New Mexico Hospital", "Presbyterian Hospital Albuquerque", "Lovelace Medical Center", "Christus St. Vincent Regional Medical Center"],
    airports: ["Albuquerque International Sunport (ABQ)"],
    localFacts: ["New Mexico follows pure comparative fault — recovery possible at any fault level", "The Big I interchange at I-25/I-40 is one of New Mexico's busiest and most crash-prone intersections", "Bernalillo County records over 15,000 crashes annually"]
  },
  {
    id: "new-york",
    city: "New York City",
    state: "New York",
    stateCode: "NY",
    county: "New York County",
    phone: "212-600-0000",
    lat: 40.7128, lng: -74.0060,
    statute: "3 years",
    pip: true,
    faultState: "pure comparative fault",
    highways: ["I-95 New England Thruway", "I-78 Holland Tunnel", "I-495 Lincoln Tunnel/Long Island Expressway", "I-278 Staten Island Expressway/Brooklyn-Queens Expressway", "I-87 New York Thruway", "Belt Parkway", "FDR Drive", "West Side Highway"],
    landmarks: ["NewYork-Presbyterian Hospital", "Bellevue Hospital Center", "Madison Square Garden", "Yankee Stadium", "Citi Field", "MetLife Stadium (NJ)", "Times Square", "Central Park", "Grand Central Terminal", "JFK International Airport"],
    neighborhoods: ["Brooklyn", "Queens", "Bronx", "Staten Island", "Harlem", "Astoria", "Flushing", "Bay Ridge", "Bensonhurst"],
    hotspots: ["BQE Brooklyn-Queens Expressway", "I-495 Long Island Expressway entire length", "FDR Drive", "Belt Parkway", "I-278 Staten Island Expressway", "Cross Bronx Expressway I-95"],
    medCenters: ["NewYork-Presbyterian Hospital", "Bellevue Hospital Center", "NYC Health + Hospitals/Elmhurst", "NYU Langone Health", "Mount Sinai Hospital"],
    airports: ["John F. Kennedy International Airport (JFK)", "LaGuardia Airport (LGA)", "Newark Liberty International Airport (EWR)"],
    localFacts: ["New York has mandatory no-fault PIP coverage with a $50,000 minimum", "New York has a 3-year statute of limitations", "New York City records over 200,000 reported crashes annually across all five boroughs"]
  },
  {
    id: "charlotte",
    city: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    county: "Mecklenburg County",
    phone: "704-600-0000",
    lat: 35.2271, lng: -80.8431,
    statute: "3 years",
    pip: false,
    faultState: "contributory negligence",
    highways: ["I-85", "I-77", "I-485 Outer Belt", "I-277 Brookshire Freeway", "US-74 Independence Boulevard", "NC-16 Providence Road", "NC-51", "Billy Graham Parkway"],
    landmarks: ["Atrium Health Carolinas Medical Center", "Novant Health Presbyterian Medical Center", "Bank of America Stadium", "Spectrum Center", "Truist Field", "Charlotte Douglas International Airport", "Carowinds"],
    neighborhoods: ["Gastonia", "Concord", "Huntersville", "Matthews", "Mint Hill", "Mooresville", "Kannapolis", "Rock Hill SC", "Monroe"],
    hotspots: ["I-485 Outer Belt full loop", "I-85 north/south through Charlotte", "I-77 at I-85 interchange", "Independence Boulevard US-74", "I-485 at I-85 interchange"],
    medCenters: ["Atrium Health Carolinas Medical Center", "Novant Health Presbyterian Medical Center", "CMC-NorthEast", "Atrium Health University City"],
    airports: ["Charlotte Douglas International Airport (CLT)"],
    localFacts: ["North Carolina is a contributory negligence state — any fault can bar your recovery", "North Carolina has a 3-year statute of limitations", "Mecklenburg County records over 30,000 crashes annually and is growing rapidly"]
  },
  {
    id: "fargo",
    city: "Fargo",
    state: "North Dakota",
    stateCode: "ND",
    county: "Cass County",
    phone: "701-600-0000",
    lat: 46.8772, lng: -96.7898,
    statute: "6 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-94", "I-29", "US-10", "US-81 32nd Avenue South", "45th Street South", "13th Avenue South"],
    landmarks: ["Sanford Medical Center Fargo", "Essentia Health Fargo", "Fargodome", "Red River", "Moorhead Bridge interchange", "Scheels Arena"],
    neighborhoods: ["West Fargo", "Moorhead MN", "Dilworth", "Casselton", "Horace", "Harwood", "Mapleton"],
    hotspots: ["I-94 at I-29 interchange", "I-29 north/south corridor", "13th Avenue South retail corridor", "32nd Avenue South", "I-94 west toward Bismarck"],
    medCenters: ["Sanford Medical Center Fargo", "Essentia Health Fargo", "MeritCare Hospital"],
    airports: ["Hector International Airport (FAR)"],
    localFacts: ["North Dakota has a 6-year statute of limitations", "Fargo's Red River Valley location creates significant blizzard and ice-storm crash risks", "Cass County averages over 3,500 crashes annually with spike in winter months"]
  },
  {
    id: "columbus",
    city: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    county: "Franklin County",
    phone: "614-600-0000",
    lat: 39.9612, lng: -82.9988,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-70", "I-71", "I-270 Outerbelt", "I-670", "US-23", "US-33 Dublin-Granville Road", "SR-315", "SR-161"],
    landmarks: ["OhioHealth Riverside Methodist Hospital", "Ohio State University Wexner Medical Center", "Nationwide Arena", "Ohio Stadium (The Horseshoe)", "Huntington Park", "Ohio Statehouse", "Short North Arts District"],
    neighborhoods: ["Dublin", "Westerville", "Gahanna", "Grove City", "Hilliard", "Powell", "New Albany", "Reynoldsburg", "Pickerington"],
    hotspots: ["I-270 Outerbelt full loop", "I-70 at I-71 interchange", "I-670 east connector", "SR-315 corridor", "US-33 Dublin-Granville Road"],
    medCenters: ["OhioHealth Riverside Methodist Hospital", "Ohio State University Wexner Medical Center", "Nationwide Children's Hospital", "Mount Carmel Health System"],
    airports: ["John Glenn Columbus International Airport (CMH)"],
    localFacts: ["Ohio has a 2-year statute of limitations for personal injury", "Franklin County records over 35,000 crashes annually", "I-270 Outerbelt is consistently Ohio's most crash-dense beltway"]
  },
  {
    id: "oklahoma-city",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    county: "Oklahoma County",
    phone: "405-600-0000",
    lat: 35.4676, lng: -97.5164,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-35", "I-40", "I-44 Turner Turnpike", "I-240", "US-77", "US-270", "Kilpatrick Turnpike OK-74", "I-235"],
    landmarks: ["OU Health University of Oklahoma Medical Center", "Integris Baptist Medical Center", "Paycom Center", "Chickasaw Bricktown Ballpark", "Scissortail Park", "Oklahoma State Capitol", "Bricktown District"],
    neighborhoods: ["Edmond", "Moore", "Norman", "Midwest City", "Del City", "Yukon", "Mustang", "Choctaw"],
    hotspots: ["I-40 at I-35 interchange", "I-240 south beltway", "I-44 at I-35", "Kilpatrick Turnpike northwest", "I-35 south toward Norman"],
    medCenters: ["OU Health University of Oklahoma Medical Center", "Integris Baptist Medical Center", "Mercy Hospital Oklahoma City", "SSM Health St. Anthony Hospital"],
    airports: ["Will Rogers World Airport (OKC)"],
    localFacts: ["Oklahoma has a 2-year statute of limitations", "Oklahoma County records over 20,000 crashes annually", "Oklahoma's severe weather including ice storms causes significant seasonal crash spikes"]
  },
  {
    id: "portland-or",
    city: "Portland",
    state: "Oregon",
    stateCode: "OR",
    county: "Multnomah County",
    phone: "503-600-0000",
    lat: 45.5051, lng: -122.6750,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-5", "I-84 Banfield Expressway", "I-205", "US-26 Sunset Highway", "OR-217 Beaverton-Tigard Highway", "OR-99W Pacific Highway", "I-405"],
    landmarks: ["OHSU Hospital", "Legacy Emanuel Medical Center", "Providence Portland Medical Center", "Providence Park (TIMBERS)", "Moda Center", "Oregon Convention Center", "Portland International Airport", "Mount Hood"],
    neighborhoods: ["Beaverton", "Gresham", "Hillsboro", "Lake Oswego", "Tigard", "Milwaukie", "Tualatin", "Troutdale", "Canby"],
    hotspots: ["I-5 at I-84 interchange (Rose Quarter)", "I-84 east corridor", "I-205 north/south", "US-26 Sunset Highway", "OR-217 Beaverton corridor"],
    medCenters: ["OHSU Hospital", "Legacy Emanuel Medical Center", "Providence Portland Medical Center", "Adventist Health Portland"],
    airports: ["Portland International Airport (PDX)"],
    localFacts: ["Oregon requires mandatory PIP coverage of $15,000", "Oregon has a 2-year statute of limitations", "Multnomah County records over 20,000 crashes annually with significant pedestrian and cyclist crashes"]
  },
  {
    id: "philadelphia",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    county: "Philadelphia County",
    phone: "215-600-0000",
    lat: 39.9526, lng: -75.1652,
    statute: "2 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-95 Delaware Expressway", "I-76 Schuylkill Expressway", "I-676 Vine Street Expressway", "US-1 Roosevelt Boulevard", "US-30 Lancaster Avenue", "I-476 Blue Route", "PA-309 Fort Washington Expressway"],
    landmarks: ["Jefferson Hospital", "Penn Presbyterian Medical Center", "Lincoln Financial Field", "Citizens Bank Park", "Wells Fargo Center", "Independence Hall", "Reading Terminal Market", "Philadelphia International Airport"],
    neighborhoods: ["Bucks County", "Montgomery County", "Delaware County", "Chester County", "Camden NJ", "Wilmington DE", "Norristown", "Trenton NJ"],
    hotspots: ["I-76 Schuylkill Expressway (The Schuylkill)", "I-95 through South Philadelphia", "US-1 Roosevelt Boulevard", "I-676 Vine Street Expressway", "I-476 Blue Route"],
    medCenters: ["Jefferson Hospital", "Penn Presbyterian Medical Center", "Temple University Hospital", "Einstein Medical Center Philadelphia"],
    airports: ["Philadelphia International Airport (PHL)"],
    localFacts: ["Pennsylvania has mandatory first-party benefits (PIP equivalent)", "Pennsylvania has a 2-year statute of limitations", "Philadelphia County records over 20,000 crashes annually; I-76 Schuylkill is nicknamed 'the Sure-Kill Expressway'"]
  },
  {
    id: "providence",
    city: "Providence",
    state: "Rhode Island",
    stateCode: "RI",
    county: "Providence County",
    phone: "401-600-0000",
    lat: 41.8240, lng: -71.4128,
    statute: "3 years",
    pip: true,
    faultState: "pure comparative fault",
    highways: ["I-95", "I-195 Davol Interchange", "I-295", "US-6 Hartford Avenue", "US-44 Putnam Pike", "Route 10", "Route 146"],
    landmarks: ["Rhode Island Hospital", "The Miriam Hospital", "Dunkin Donuts Center", "Amica Mutual Pavilion", "WaterFire Providence", "Brown University", "Rhode Island State House"],
    neighborhoods: ["Cranston", "Pawtucket", "North Providence", "Johnston", "Warwick", "East Providence", "Woonsocket", "Cumberland"],
    hotspots: ["I-95 at I-195 interchange", "I-195 east corridor", "I-295 loop", "Route 10 connector", "US-6 Hartford Avenue"],
    medCenters: ["Rhode Island Hospital", "The Miriam Hospital", "Women & Infants Hospital", "Kent Hospital Warwick"],
    airports: ["T.F. Green Airport (PVD)"],
    localFacts: ["Rhode Island has a 3-year statute of limitations", "Rhode Island requires mandatory PIP/no-fault coverage", "Providence County averages over 12,000 crashes annually in a very dense road network"]
  },
  {
    id: "columbia",
    city: "Columbia",
    state: "South Carolina",
    stateCode: "SC",
    county: "Richland County",
    phone: "803-600-0000",
    lat: 34.0007, lng: -81.0348,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-20", "I-26", "I-77", "US-1", "US-378 David H. McLeod Boulevard", "SC-277 Broad River Road", "Bush River Road", "Two Notch Road"],
    landmarks: ["Prisma Health Richland Hospital", "Lexington Medical Center", "Colonial Life Arena", "Segra Park", "South Carolina State Capitol", "University of South Carolina Campus", "Riverbanks Zoo"],
    neighborhoods: ["Lexington", "Irmo", "Forest Acres", "Cayce", "West Columbia", "Blythewood", "Chapin", "Elgin"],
    hotspots: ["I-20 at I-26 interchange", "I-77 north/south corridor", "Two Notch Road US-1 east", "Bush River Road", "I-20 at I-77"],
    medCenters: ["Prisma Health Richland Hospital", "Lexington Medical Center", "Providence Health Columbia", "MUSC Health Columbia Medical Center"],
    airports: ["Columbia Metropolitan Airport (CAE)"],
    localFacts: ["South Carolina has a 3-year statute of limitations", "South Carolina has one of the higher traffic fatality rates per mile driven in the Southeast", "Richland County records over 10,000 crashes annually"]
  },
  {
    id: "sioux-falls",
    city: "Sioux Falls",
    state: "South Dakota",
    stateCode: "SD",
    county: "Minnehaha County",
    phone: "605-600-0000",
    lat: 43.5446, lng: -96.7311,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-90", "I-29", "I-229", "US-16 West 12th Street", "US-81", "SD-42 41st Street", "SD-11 Minnesota Avenue"],
    landmarks: ["Sanford USD Medical Center", "Avera McKennan Hospital", "Denny Sanford Premier Center", "Falls Park", "Great Plains Zoo", "USS South Dakota Battleship Memorial"],
    neighborhoods: ["Brandon", "Tea", "Harrisburg", "Dell Rapids", "Lennox", "Hartford", "Crooks"],
    hotspots: ["I-29 at I-90 interchange", "I-229 east corridor", "41st Street SD-42 retail corridor", "Minnesota Avenue SD-11", "I-90 west toward Rapid City"],
    medCenters: ["Sanford USD Medical Center", "Avera McKennan Hospital", "Sanford Clinic North"],
    airports: ["Sioux Falls Regional Airport Joe Foss Field (FSD)"],
    localFacts: ["South Dakota has a 3-year statute of limitations", "Sioux Falls is growing rapidly, increasing crash frequency significantly", "Minnehaha County averages over 5,000 crashes annually"]
  },
  {
    id: "memphis",
    city: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    county: "Shelby County",
    phone: "901-600-0000",
    lat: 35.1495, lng: -90.0490,
    statute: "1 year",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-40", "I-55 Mississippi River Bridge", "I-240 Beltway", "US-70 Summer Avenue", "US-72 Poplar Avenue", "US-78 Lamar Avenue", "Sam Cooper Boulevard", "Germantown Parkway"],
    landmarks: ["Regional One Health", "Methodist Le Bonheur Healthcare", "FedExForum", "AutoZone Park", "Graceland", "Beale Street", "Memphis International Airport", "Mud Island"],
    neighborhoods: ["Germantown", "Bartlett", "Collierville", "Cordova", "Millington", "Southaven MS", "Olive Branch MS", "Marion AR"],
    hotspots: ["I-240 beltway", "I-40 at I-240 interchange", "I-55 Mississippi River Bridge approach", "Poplar Avenue US-72 corridor", "Summer Avenue US-70 corridor"],
    medCenters: ["Regional One Health", "Methodist Le Bonheur Healthcare", "Baptist Memorial Hospital", "St. Francis Hospital Memphis"],
    airports: ["Memphis International Airport (MEM)"],
    localFacts: ["Tennessee has a 1-year statute of limitations — one of the shortest in the nation, act immediately", "Tennessee follows modified comparative fault at 50% bar", "Shelby County records over 30,000 crashes annually"]
  },
  {
    id: "houston",
    city: "Houston",
    state: "Texas",
    stateCode: "TX",
    county: "Harris County",
    phone: "713-600-0000",
    lat: 29.7604, lng: -95.3698,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-10 Katy Freeway", "I-45 Gulf Freeway", "I-610 Inner Loop", "US-59/I-69 Southwest Freeway", "Beltway 8 Sam Houston Tollway", "TX-288", "I-69 North Freeway", "TX-6"],
    landmarks: ["Houston Methodist Hospital", "Memorial Hermann Texas Medical Center", "NRG Stadium", "Toyota Center", "Minute Maid Park", "Houston Livestock Show and Rodeo", "NASA Johnson Space Center", "Houston Galleria"],
    neighborhoods: ["Sugar Land", "The Woodlands", "Pearland", "Pasadena", "Katy", "Baytown", "League City", "Missouri City", "Conroe"],
    hotspots: ["I-10 Katy Freeway (widest highway in the world)", "I-610 Inner Loop entire loop", "I-45 Gulf Freeway south corridor", "Beltway 8 Sam Houston Tollway", "I-69/US-59 Southwest Freeway"],
    medCenters: ["Houston Methodist Hospital", "Memorial Hermann Hospital", "Ben Taub General Hospital", "UTHealth Houston Medical School"],
    airports: ["George Bush Intercontinental Airport (IAH)", "William P. Hobby Airport (HOU)"],
    localFacts: ["Texas has a 2-year statute of limitations", "Harris County records over 70,000 crashes annually — among the highest of any county in the US", "The I-10 Katy Freeway is 26 lanes wide at its widest point"]
  },
  {
    id: "salt-lake-city",
    city: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    county: "Salt Lake County",
    phone: "801-600-0000",
    lat: 40.7608, lng: -111.8910,
    statute: "4 years",
    pip: true,
    faultState: "modified comparative fault",
    highways: ["I-15", "I-80", "I-215 Beltway", "I-84", "US-89 State Street", "US-40", "Bangerter Highway UT-154", "Mountain View Corridor"],
    landmarks: ["University of Utah Hospital", "Intermountain Healthcare", "Delta Center", "Smith's Ballpark", "Temple Square", "Salt Lake City International Airport", "Great Salt Lake", "Park City (30 min)"],
    neighborhoods: ["Sandy", "West Valley City", "Provo", "Murray", "Ogden", "Layton", "Orem", "Taylorsville", "Millcreek"],
    hotspots: ["I-15 through downtown SLC", "I-215 Beltway full loop", "I-80 east toward mountains", "I-15 at I-80 interchange", "Bangerter Highway corridor"],
    medCenters: ["University of Utah Hospital", "Intermountain Medical Center", "LDS Hospital", "St. Mark's Hospital Salt Lake City"],
    airports: ["Salt Lake City International Airport (SLC)"],
    localFacts: ["Utah has a 4-year statute of limitations for personal injury", "Utah requires PIP/no-fault coverage", "Salt Lake County records over 25,000 crashes annually; winter canyon conditions on I-80 are extremely dangerous"]
  },
  {
    id: "burlington",
    city: "Burlington",
    state: "Vermont",
    stateCode: "VT",
    county: "Chittenden County",
    phone: "802-600-0000",
    lat: 44.4759, lng: -73.2121,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-89", "US-2 Williston Road", "US-7 Shelburne Road", "VT-15 Pearl Street", "VT-116 Airport Drive", "Circumferential Highway"],
    landmarks: ["UVM Medical Center", "Vermont Health Access", "Champlain Valley Fair", "Church Street Marketplace", "Burlington Waterfront Park", "Lake Champlain", "Burlington International Airport"],
    neighborhoods: ["South Burlington", "Williston", "Shelburne", "Essex Junction", "Winooski", "Colchester", "Milton", "Hinesburg"],
    hotspots: ["I-89 through Burlington/South Burlington", "US-2 Williston Road corridor", "US-7 Shelburne Road", "Circumferential Highway", "I-89 at Taft Corners Exit"],
    medCenters: ["UVM Medical Center", "Porter Medical Center Middlebury", "Northwestern Medical Center St. Albans"],
    airports: ["Burlington International Airport (BTV)"],
    localFacts: ["Vermont has a 3-year statute of limitations", "Vermont winters produce severe black ice conditions statewide", "Chittenden County averages over 2,500 crashes annually — small numbers but high impact on the small community"]
  },
  {
    id: "virginia-beach",
    city: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    county: "Virginia Beach City",
    phone: "757-600-0000",
    lat: 36.8529, lng: -75.9780,
    statute: "2 years",
    pip: false,
    faultState: "contributory negligence",
    highways: ["I-264 Virginia Beach-Norfolk Expressway", "I-64", "US-58 Virginia Beach Boulevard", "US-13 Shore Drive", "US-17", "Hampton Roads Bridge-Tunnel", "I-664 Monitor-Merrimac Bridge-Tunnel"],
    landmarks: ["Sentara Virginia Beach General Hospital", "Bon Secours Maryview Medical Center Norfolk", "Virginia Beach Oceanfront", "Virginia Beach Convention Center", "Norfolk Naval Station", "Virginia Aquarium", "Pembroke Mall area"],
    neighborhoods: ["Chesapeake", "Norfolk", "Suffolk", "Hampton", "Newport News", "Portsmouth", "Isle of Wight County"],
    hotspots: ["I-264 Virginia Beach-Norfolk Expressway", "Hampton Roads Bridge-Tunnel I-64", "US-58 Virginia Beach Boulevard", "I-64 at I-264 interchange", "US-13 Shore Drive"],
    medCenters: ["Sentara Virginia Beach General Hospital", "Bon Secours DePaul Medical Center", "Sentara Norfolk General Hospital", "Children's Hospital of The King's Daughters"],
    airports: ["Norfolk International Airport (ORF)"],
    localFacts: ["Virginia is a contributory negligence state — any fault on your part can bar recovery", "Virginia has a 2-year statute of limitations", "Virginia Beach City and Hampton Roads area record over 20,000 crashes annually"]
  },
  {
    id: "seattle",
    city: "Seattle",
    state: "Washington",
    stateCode: "WA",
    county: "King County",
    phone: "206-600-0000",
    lat: 47.6062, lng: -122.3321,
    statute: "3 years",
    pip: true,
    faultState: "pure comparative fault",
    highways: ["I-5", "I-90 Mount Baker Tunnel", "I-405 Eastside", "SR-520 Evergreen Point Floating Bridge", "SR-99 Aurora Avenue/Battery Street Tunnel", "SR-167", "US-2"],
    landmarks: ["Harborview Medical Center", "UW Medical Center", "Lumen Field", "T-Mobile Park", "Climate Pledge Arena", "Space Needle", "Pike Place Market", "Amazon Headquarters", "Seattle-Tacoma International Airport"],
    neighborhoods: ["Bellevue", "Tacoma", "Renton", "Kent", "Kirkland", "Redmond", "Bothell", "Everett", "Shoreline", "Burien"],
    hotspots: ["I-5 through downtown Seattle", "I-405 entire Eastside corridor", "SR-520 floating bridge", "I-90 Mount Baker Tunnel", "SR-99 Aurora Avenue corridor"],
    medCenters: ["Harborview Medical Center", "UW Medical Center", "Swedish Medical Center", "Virginia Mason Franciscan Health"],
    airports: ["Seattle-Tacoma International Airport (SEA)", "Boeing Field King County International Airport (BFI)"],
    localFacts: ["Washington requires PIP coverage and follows pure comparative fault", "Washington has a 3-year statute of limitations", "King County records over 40,000 crashes annually; Seattle's tech boom has significantly increased traffic density"]
  },
  {
    id: "charleston",
    city: "Charleston",
    state: "West Virginia",
    stateCode: "WV",
    county: "Kanawha County",
    phone: "304-600-0000",
    lat: 38.3498, lng: -81.6326,
    statute: "2 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-64", "I-77", "I-79", "US-60 MacCorkle Avenue", "US-119 Corridor G", "WV-61 Kanawha Turnpike", "Patrick Street Plaza"],
    landmarks: ["CAMC General Hospital", "Thomas Memorial Hospital", "Charleston Civic Center", "Appalachian Power Park", "West Virginia State Capitol", "Kanawha River", "Yeager Airport"],
    neighborhoods: ["South Charleston", "St. Albans", "Hurricane", "Dunbar", "Nitro", "Cross Lanes", "Teays Valley", "Sissonville"],
    hotspots: ["I-64 at I-77 interchange", "US-60 MacCorkle Avenue", "I-79 north corridor", "US-119 Corridor G south", "Patrick Street corridor"],
    medCenters: ["CAMC General Hospital", "Thomas Memorial Hospital", "Charleston Area Medical Center Women and Children's"],
    airports: ["Yeager Airport (CRW)"],
    localFacts: ["West Virginia has a 2-year statute of limitations", "West Virginia mountain terrain and winding roads contribute to a high per-capita crash rate", "Kanawha County averages over 5,000 crashes annually"]
  },
  {
    id: "milwaukee",
    city: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    county: "Milwaukee County",
    phone: "414-600-0000",
    lat: 43.0389, lng: -87.9065,
    statute: "3 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-94", "I-43 North-South Freeway", "I-894 Mitchell Freeway", "I-794 Lakefront Freeway", "US-41 North Avenue", "WI-894 Zoo Interchange", "Hales Corners Bypass"],
    landmarks: ["Froedtert Hospital", "Ascension SE Wisconsin Hospital", "American Family Field", "Fiserv Forum", "Milwaukee Art Museum", "Summerfest Grounds Henry Maier Festival Park", "Milwaukee Mitchell International Airport"],
    neighborhoods: ["Wauwatosa", "West Allis", "Greenfield", "Oak Creek", "Franklin", "Muskego", "New Berlin", "Brookfield", "Waukesha"],
    hotspots: ["Zoo Interchange I-94/I-894/US-45", "I-43 north/south corridor", "I-94 east toward Chicago", "I-794 Lakefront connector", "US-41 North Avenue corridor"],
    medCenters: ["Froedtert Hospital", "Ascension SE Wisconsin Hospital", "Children's Wisconsin", "Aurora St. Luke's Medical Center"],
    airports: ["Milwaukee Mitchell International Airport (MKE)"],
    localFacts: ["Wisconsin has a 3-year statute of limitations", "The Zoo Interchange is one of the busiest and most crash-prone interchanges in the Midwest", "Milwaukee County records over 20,000 crashes annually"]
  },
  {
    id: "cheyenne",
    city: "Cheyenne",
    state: "Wyoming",
    stateCode: "WY",
    county: "Laramie County",
    phone: "307-600-0000",
    lat: 41.1400, lng: -104.8197,
    statute: "4 years",
    pip: false,
    faultState: "modified comparative fault",
    highways: ["I-25", "I-80", "US-30 Lincoln Way", "US-85 Greeley Highway", "WY-212 Dell Range Boulevard", "College Drive", "Yellowstone Road"],
    landmarks: ["Cheyenne Regional Medical Center", "United Medical Center", "Cheyenne Frontier Days Arena", "Wyoming State Capitol", "F.E. Warren Air Force Base", "Cheyenne Botanic Gardens"],
    neighborhoods: ["Warren AFB area", "Ranchettes", "South Greeley Highway corridor", "Happy Jack area", "Pine Bluffs", "Burns", "Albin"],
    hotspots: ["I-25 at I-80 interchange", "I-80 through Cheyenne toward Colorado", "Dell Range Boulevard corridor", "Lincoln Way US-30", "US-85 Greeley Highway south"],
    medCenters: ["Cheyenne Regional Medical Center", "United Medical Center", "Wyoming Medical Center Casper (2 hours north)"],
    airports: ["Cheyenne Regional Airport Jerry Olson Field (CYS)"],
    localFacts: ["Wyoming has a 4-year statute of limitations", "I-80 through Wyoming is one of the most dangerous stretches of interstate in the country due to wind and blizzards", "Laramie County averages over 2,000 crashes annually despite small population"]
  }
];

if (typeof module !== 'undefined') module.exports = CITY_DATA;
